<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Requisitos/policies de autorização usam Microsoft.AspNetCore.Authorization. -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.12.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Worfair.BuildingBlocks.Domain\Worfair.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
