// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Worfair.Modules.Recruitment.Infrastructure.Persistence;

#nullable disable

namespace Worfair.Modules.Recruitment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecruitmentDbContext))]
    [Migration("20260824192620_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Worfair.BuildingBlocks.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_on IS NULL");

                    b.ToTable("outbox_messages", "recruitment");
                });

            modelBuilder.Entity("Worfair.Modules.Recruitment.Domain.Aggregates.Candidate.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text")
                        .HasColumnName("resume_url");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_candidates_tenant_status");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_candidates_tenant_user");

                    b.ToTable("candidates", "recruitment");
                });

            modelBuilder.Entity("Worfair.Modules.Recruitment.Domain.Aggregates.Interview.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("JobRequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_requisition_id");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CandidateId")
                        .HasDatabaseName("ix_interviews_tenant_candidate");

                    b.HasIndex("TenantId", "ScheduledAtUtc")
                        .HasDatabaseName("ix_interviews_tenant_date");

                    b.ToTable("interviews", "recruitment");
                });

            modelBuilder.Entity("Worfair.Modules.Recruitment.Domain.Aggregates.JobRequisition.JobRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloseReason")
                        .HasColumnType("text")
                        .HasColumnName("close_reason");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_job_requisitions_tenant_company");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_job_requisitions_tenant_status");

                    b.ToTable("job_requisitions", "recruitment");
                });

            modelBuilder.Entity("Worfair.Modules.Recruitment.Domain.Aggregates.Candidate.Candidate", b =>
                {
                    b.OwnsMany("Worfair.Modules.Recruitment.Domain.Aggregates.Candidate.CandidateStageHistoryEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("ChangedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at");

                            b1.Property<Guid>("ChangedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by");

                            b1.Property<int>("FromStatus")
                                .HasColumnType("integer")
                                .HasColumnName("from_status");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<int>("ToStatus")
                                .HasColumnType("integer")
                                .HasColumnName("to_status");

                            b1.Property<Guid>("candidate_id")
                                .HasColumnType("uuid")
                                .HasColumnName("candidate_id");

                            b1.HasKey("Id");

                            b1.HasIndex("candidate_id")
                                .HasDatabaseName("ix_candidate_stage_history_candidate");

                            b1.ToTable("candidate_stage_history", "recruitment");

                            b1.WithOwner()
                                .HasForeignKey("candidate_id");
                        });

                    b.Navigation("History");
                });

            modelBuilder.Entity("Worfair.Modules.Recruitment.Domain.Aggregates.Interview.Interview", b =>
                {
                    b.OwnsMany("Worfair.Modules.Recruitment.Domain.Aggregates.Interview.InterviewFeedback", "Feedbacks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("InterviewerUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("interviewer_user_id");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("notes");

                            b1.Property<short>("Rating")
                                .HasColumnType("smallint")
                                .HasColumnName("rating");

                            b1.Property<DateTime>("SubmittedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("submitted_at");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<Guid>("interview_id")
                                .HasColumnType("uuid")
                                .HasColumnName("interview_id");

                            b1.HasKey("Id");

                            b1.HasIndex("interview_id", "InterviewerUserId")
                                .IsUnique()
                                .HasDatabaseName("uq_interview_feedbacks_interview_interviewer");

                            b1.ToTable("interview_feedbacks", "recruitment");

                            b1.WithOwner()
                                .HasForeignKey("interview_id");
                        });

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Worfair.Modules.Recruitment.Domain.Aggregates.JobRequisition.JobRequisition", b =>
                {
                    b.OwnsOne("Worfair.Modules.Recruitment.Domain.ValueObjects.SalaryRange", "SalaryRange", b1 =>
                        {
                            b1.Property<Guid>("JobRequisitionId")
                                .HasColumnType("uuid");

                            b1.HasKey("JobRequisitionId");

                            b1.ToTable("job_requisitions", "recruitment");

                            b1.WithOwner()
                                .HasForeignKey("JobRequisitionId");

                            b1.OwnsOne("Worfair.Modules.Recruitment.Domain.ValueObjects.Money", "Maximum", b2 =>
                                {
                                    b2.Property<Guid>("SalaryRangeJobRequisitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("salary_max");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("salary_max_currency");

                                    b2.HasKey("SalaryRangeJobRequisitionId");

                                    b2.ToTable("job_requisitions", "recruitment");

                                    b2.WithOwner()
                                        .HasForeignKey("SalaryRangeJobRequisitionId");
                                });

                            b1.OwnsOne("Worfair.Modules.Recruitment.Domain.ValueObjects.Money", "Minimum", b2 =>
                                {
                                    b2.Property<Guid>("SalaryRangeJobRequisitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("salary_min");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("salary_currency");

                                    b2.HasKey("SalaryRangeJobRequisitionId");

                                    b2.ToTable("job_requisitions", "recruitment");

                                    b2.WithOwner()
                                        .HasForeignKey("SalaryRangeJobRequisitionId");
                                });

                            b1.Navigation("Maximum");

                            b1.Navigation("Minimum")
                                .IsRequired();
                        });

                    b.OwnsMany("Worfair.Modules.Recruitment.Domain.Aggregates.JobRequisition.HiringTeamMember", "HiringTeam", b1 =>
                        {
                            b1.Property<Guid>("job_requisition_id")
                                .HasColumnType("uuid")
                                .HasColumnName("job_requisition_id");

                            b1.Property<Guid>("RecruiterUserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("recruiter_user_id");

                            b1.Property<DateTime>("AddedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("added_at");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("job_requisition_id", "RecruiterUserId");

                            b1.ToTable("hiring_team_members", "recruitment");

                            b1.WithOwner()
                                .HasForeignKey("job_requisition_id");
                        });

                    b.Navigation("HiringTeam");

                    b.Navigation("SalaryRange")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
